import type { Metadata } from "next";
import { Montserrat, Zen_Kaku_Gothic_New } from "next/font/google";
import clsx from "clsx";
import StoreProvider from "./StoreProvider";
import { Header, ThemeProvider } from "@/components/shared";

import "@/styles/index.scss";

const montserratSans = Montserrat({
  variable: "--font-montserrat-sans",
  subsets: ["cyrillic"],
});

const zenKakuGothicNew = Zen_Kaku_Gothic_New({
  variable: "--font-zen-kaku",
  weight: ["400"],
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: {
    template: "%s | Mini Projects",
    default: "Mini Projects",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={clsx(montserratSans.variable, zenKakuGothicNew.variable)}
      >
        <StoreProvider>
          <ThemeProvider>
            <Header />
            {children}
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
