import type { Metadata } from "next";
import { Montserrat, Zen_Kaku_Gothic_New } from "next/font/google";
import { Header, ThemeProvider } from "@/app/components/shared";
import clsx from "clsx";

import "@/app/styles/index.scss";

const montserratSans = Montserrat({
  variable: "--font-montserrat-sans",
  subsets: ["cyrillic"],
});

const zenKakuGothicNew = Zen_Kaku_Gothic_New({
  variable: "--font-zen-kaku",
  weight: ["400"],
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Mini Projects",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={clsx(montserratSans.variable, zenKakuGothicNew.variable)}
      >
        <ThemeProvider>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
